### ISSUE TITLE
Python- Fehler: FileNotFoundError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by schorsch2** [EZUSoft/SaxonyCadastralParcels#3]
Wir erhalten eine Fehlermeldung beim Versuch, Katasterdaten aus Sachsen zu beziehen und als DXF abzulegen:
`Ein Fehler trat bei der Ausführung von Python-Code auf: 

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/wei.IBE/AppData/Local/Temp/{D5E6A1F8-392F-4241-A0BD-5CED09CFABC7}/d5d4ef1f-e028-4236-ba3b-8989aa85f1fd_1.csv' 
Traceback (most recent call last):
  File "C:\Users/wei.IBE/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SaxonyCadastralParcels\uiFlurst4BL.py", line 389, in btnStart_clicked
    Antw = GemWorker (self, self.glAktLandKenn, self.fncAktLandName(), Liste, ZielPfad, self.chkSHP.isChecked(), self.chkDXF.isChecked(),self.chkMergeFlur.isChecked())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/wei.IBE/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SaxonyCadastralParcels\clsWorker.py", line 530, in GemWorker
    genDXF4Gemarkung (uiParent, unzipdir, shpList, expPfad + datZeile[idxLokName] + '.dxf')
  File "C:\Users/wei.IBE/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SaxonyCadastralParcels\clsWorker.py", line 363, in genDXF4Gemarkung
    concatDXFBeschriftung(qDxfDat,qCsvDat,zDxfDat,sDat)
  File "C:\Users/wei.IBE/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SaxonyCadastralParcels\clsWorker.py", line 633, in concatDXFBeschriftung
    csvArray = fncUniDatReadAll23(qCsvDat,'utf-8')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/wei.IBE/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SaxonyCadastralParcels\fnc4all.py", line 394, in fncUniDatReadAll23
    tmp = open(DatName, "r", encoding=sEncode)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/wei.IBE/AppData/Local/Temp/{D5E6A1F8-392F-4241-A0BD-5CED09CFABC7}/d5d4ef1f-e028-4236-ba3b-8989aa85f1fd_1.csv'

Python-Version: 3.12.3 (main, Apr 14 2024, 17:21:43) [MSC v.1938 64 bit (AMD64)] 
QGIS-Version: 3.36.3-Maidenhead Maidenhead, 2df96554 

Python-Pfad:
C:\Users/wei.IBE/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\generate_swmm_inp
C:/OSGeo4W/apps/qgis/./python
C:/Users/wei.IBE/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/wei.IBE/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\bin\python312.zip
C:\OSGeo4W\apps\Python312\DLLs
C:\OSGeo4W\apps\Python312\Lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python312
C:\OSGeo4W\apps\Python312\Lib\site-packages
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/wei.IBE/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\wei.IBE\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qfieldsync\libqfieldsync.whl`

**Comment by EZUSoft** [comment]
ich kann den Fehler nachvollziehen und schaue nach der Ursache.

**Comment by EZUSoft** [comment]
Ich kann das Problem leider nicht nachvollziehen.
Du kannst nur versuchen das Problem einzugrenzen:
1) Rechnerneustart
2) Andere Gemarkung
3) Konvertierung nach Shape
4) Test Thüringen
....
Ich habe trotzdem eine neue Version ( V0.4.3) hochgeladen, welche in den nächsten tagen freigeschalten wird. Da sollte der Fehler zumindest abgefangen werden.

**Comment by schorsch2** [comment]
>     1. Rechnerneustart
ändert leider nichts - auch anderer Rechner klappt nicht 
>     2. Andere Gemarkung
auch gleiches Ergebnis
>     3. Konvertierung nach Shape
der Import als Shape funktioniert
>     4. Test Thüringen
funktioniert auch nicht

ich lege mal einen Screenshot bei:
![grafik](https://github.com/EZUSoft/SaxonyCadastralParcels/assets/13661057/4cbfd761-a80d-4f62-b74e-f6b6b1e3ab30)
mir fällt auf, dass die im Temp- Ordner befindlichen Dateien alle nach einem Namensmuster erzeugt sind d019... Die nicht gefundene Datei dagegen hat ein anderes Namensmuster b8b3... ist das Absicht?

**Comment by schorsch2** [comment]
Die Fehlermeldung zum Screenshot war am Schluss:
`FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/wei.IBE/AppData/Local/Temp/{D5E6A1F8-392F-4241-A0BD-5CED09CFABC7}/b8b3fcdf-e523-47ef-8fdc-7c61a9281917_1.dxf'`

**Comment by schorsch2** [comment]
mit der Version 0.4.3 erscheinen neue Fehlermeldungen:
![grafik](https://github.com/EZUSoft/SaxonyCadastralParcels/assets/13661057/5b720a49-b024-4a67-af53-03f178f7299a)

![grafik](https://github.com/EZUSoft/SaxonyCadastralParcels/assets/13661057/bf1889d3-6c3b-4a2e-90cd-e364cc69f480)

und am Schluss nochmal etwas von Phyton:
`FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/wei.IBE/AppData/Local/Temp/{D5E6A1F8-392F-4241-A0BD-5CED09CFABC7}/h.txt'`

**Comment by schorsch2** [comment]
Es erscheint auch eine Art Zusammenfassung:
![grafik](https://github.com/EZUSoft/SaxonyCadastralParcels/assets/13661057/92c67a05-8ddd-4919-ae77-5a08a0218d9b)

**Comment by schorsch2** [comment]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.38.0-Grenoble | QGIS-Codeversion | 37aa6188bc
-- | -- | -- | --
Qt-Version | 5.15.13
Python-Version | 3.12.4
Kompiliert mit GDAL/OGR | 3.9.0 | Läuft mit GDAL/OGR | 3.9.1
PROJ-Version | 9.4.0
EPSG-Registraturdatenbankversion | v11.004 (2024-02-24)
GEOS-Version | 3.12.2-CAPI-1.18.2
SQLite-Version | 3.45.1
PDAL-Version | 2.6.3
PostgreSQL-Client-Version | 16.2
SpatiaLite-Version | 5.1.0
QWT-Version | 6.2.0
QScintilla2-Version | 2.14.1
BS-Version | Windows 11 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
alkisplugin | 2.0.56
dzetsaka | 3.70
generate_swmm_inp | 0.35
GeoBasis_Loader | 0.8
Hqgis | 1.2.3
ImportPhotos | 3.0.6
linking_relation_editor | v1.3.0
lockzoom | 3.0.4
m150xml | 2.4
postgis_geoprocessing | 0.9
PostNAS_Search | 1.4.0
processing_saga_nextgen | 1.0.0
profiletool | 4.2.6
qfieldsync | v4.9.1
qkan | 3.3.7
QuickOSM | 2.2.3
radolan2map | 1.8
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
geocatbridge | 4.4.2
SaxonyCadastralParcels | 0.4.3

</body></html>QGIS-Version

**Comment by EZUSoft** [comment]
Es ist ein Fehler der (offenbar) nur bei dir auftritt. Was mich wundert ist, dass es auch auf einem Rechner bei dir nicht läuft.
Die Fehlermeldung sehen nach Windows aus. Der Screenshot der Dateien eher nach Linux!?
Was auffällt ist der '.' beim Userverzeichnis "wei.IBE". Sieht exotisch aus.
Lief es schon mal an deinem Rechner?
Letztendlich läuft es auf einen Fehler im GDAL`processing.run('gdal:convertformat,...)` hinaus.

... und falls du unter Windows arbeitest gibt es als Alternative **GeoTKF**

**Comment by schorsch2** [comment]
Alles ist unter Windows, auch der Screenshot der Dateien. Der exotische Punkt war noch nie ein Problem und existiert auf dem zweiten Arbeitsplatz auch nicht, weil dort ein anderer Benutzer arbeitet. Es lief schon auf beiden Rechnern, wird aber nicht so oft verwendet.
Danke für den Hinweis mit GeoTKF, damit kann ich vorerst auch arbeiten.
